-- Self Join

CREATE DATABASE IF NOT EXISTS Self_Join; 
USE Self_Join;

CREATE TABLE EMPLOYEE_INFO(
	ID INT,
    NAME VARCHAR(20),
    MANAGER_ID INT
);

INSERT INTO EMPLOYEE_INFO
(ID,NAME,MANAGER_ID)
VALUES
(101,"ADAM",103),
(102,"BOB",104),
(103,"CASEY",NULL),
(104,"DONALD",103);

SELECT a.NAME AS MANAGER_NAME,b.NAME
FROM EMPLOYEE_INFO AS a
JOIN EMPLOYEE_INFO AS b
ON a.ID = b.MANAGER_ID;

-- OUTPUT:
-- CASEY	ADAM
-- DONALD	BOB
-- CASEY	DONALD 